services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app
      - JWT_SECRET=testsecret
      - PORT=4000
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"
    command: sh -c "npm run db:init && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NUXT_PROXY_TARGET=http://backend:4000/api
    restart: unless-stopped
    environment:
      - NITRO_PORT=3000
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
